# -*- coding: utf-8 -*-
"""food_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWbCH3vb_vrvoVz74NYw-A2rtOT6ScWt
"""

!pip install ultralytics roboflow

from ultralytics import YOLO
from roboflow import Roboflow

rf = Roboflow(api_key="WhkO46oGArsxkjHLp95p")
project = rf.workspace("indianfood").project("indian_food-pwzlc")
version = project.version(2)
dataset = version.download("yolov8")

model = YOLO("yolov8n.pt")

# Train on your food dataset
model.train(
    data=dataset.location + "/data.yaml",  # path to data.yaml
    epochs=50,                             # you can increase if needed
    imgsz=640                              # image size
)

# Run prediction on a test image
results = model.predict(source="/content/Indian_food-2/test/images", show=True, conf=0.5)



model = YOLO("yolov8n.pt")

from google.colab import drive
drive.mount('/content/drive')

!cp /content/runs/detect/train/weights/best.pt /content/drive/MyDrive/

# copy best weights into Drive for permanent storage
!cp /content/runs/detect/train/weights/best.pt /content/drive/MyDrive/

from ultralytics import YOLO

# load the trained model
model = YOLO("/content/drive/MyDrive/best.pt")

from google.colab import files
uploaded = files.upload()

from google.colab import files

uploaded = files.upload()  # choose your image (mytest.jpg)

# check uploaded filename
import os
print(list(uploaded.keys()))

# run prediction
results = model.predict(source=list(uploaded.keys())[0], conf=0.5, save=True)
results[0].show()

